# Generated by Django 2.1.5 on 2019-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomNews', '0003_auto_20190204_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='telecomNews.media.images'),
        ),
    ]
