# Generated by Django 2.1.5 on 2019-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecomNews', '0004_auto_20190204_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='telecomNews/media/images'),
        ),
    ]
